name: Build, Push, and Trigger Coolify Deployment

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to the self-hosted Docker registry
      - name: Log in to Self-Hosted Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build \
          --no-cache \
          -t ${{ secrets.REGISTRY_URL }}/moneysky/moneysky:latest .

      # Push the Docker image to the self-hosted registry
      - name: Push Docker image to Self-Hosted Registry
        run: |
          docker push ${{ secrets.REGISTRY_URL }}/moneysky/moneysky:latest

      # Trigger deployment in Coolify
      - name: Trigger Coolify Deployment
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_BEARER_TOKEN }}" \
            ${{ secrets.COOLIFY_WEBHOOK_URL }}
