name: Tests

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches-ignore: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: xdebug

      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader
          npm install
          npm run build

      - name: Stan
        run: |
          composer run stan
      - name: Tests
        run: |
          touch database/moneysky_test.sqlite
          php artisan test
      - name: Type check
        run: |
          ./vendor/bin/pest --type-coverage --min=100
